packages: []

minimumReleaseAge: 1440
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: true
sideEffectsCache: false

allowBuilds:
  cypress: true
  esbuild: true

onlyBuiltDependencies:
  - cypress
  - esbuild
